# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  git-absorb = {
    pname = "git-absorb";
    version = "0.9.0";
    src = fetchFromGitHub {
      owner = "tummychow";
      repo = "git-absorb";
      rev = "0.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-jAR+Vq6SZZXkseOxZVJSjsQOStIip8ThiaLroaJcIfc=";
    };
  };
  git-branchless = {
    pname = "git-branchless";
    version = "v0.10.0";
    src = fetchFromGitHub {
      owner = "arxanas";
      repo = "git-branchless";
      rev = "v0.10.0";
      fetchSubmodules = false;
      sha256 = "sha256-8uv+sZRr06K42hmxgjrKk6FDEngUhN/9epixRYKwE3U=";
    };
  };
  git-revise = {
    pname = "git-revise";
    version = "0.8.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/g/git_revise/git_revise-0.8.0.tar.gz";
      sha256 = "sha256-MjmxgJzWWbM/bzI9O/ylx+Op6y6s4iPPY7NG+RyMgxw=";
    };
  };
}
