[git-absorb]
src.github = "tummychow/git-absorb"
fetch.github = "tummychow/git-absorb"

[git-branchless]
src.github = "arxanas/git-branchless"
fetch.github = "arxanas/git-branchless"

[git-revise]
src.pypi = "git-revise"
src.from_pattern = "^(.*)$"
src.to_pattern = "v\\1"
fetch.github = "mystor/git-revise"
